version: '3.7'
services:

  # PHP & NodeJS Service
  app:
    build:
      context: .
    tty: true
    restart: unless-stopped
    working_dir: /programming-proficiency-test
    volumes:
      - ${PWD}:/programming-proficiency-test
  frontend:
    build: ./resources
    container_name: vue_frontend
    ports:
      - 8080:8080
    command: "npm run dev"
